#!/usr/bin/env python3
"""Write the proposed CI egress allowlist from recorded actions.

Every rule is a destination a recorded job actually reached, carrying the job, the
process, and the workflow step that reached it. Destinations reached by the hosted
runner or by the container runtime are listed separately, because they belong to
whoever owns the runner network rather than to this repository.

Usage:
    python3 .garnet/tools/build_allowlist.py > .garnet/egress-allowlist.proposed.yaml
"""

import collections
import contextlib
import io
import json
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
import query  # noqa: E402

REASONS = {
    "github.com": "crates.io index over git, plus release downloads",
    "dualstack.k.sni.global.fastly.net": "crates.io CDN for crate downloads",
    "api.github.com": "release lookup by cargo-binstall",
    "release-assets.githubusercontent.com": "release asset download",
    "pypi.org": "Python package index, reached by uv during dependency install",
    "dualstack.python.map.fastly.net": "PyPI CDN for wheel downloads",
    "registry-1.docker.io": "container image pull for the Python SDK's build container",
    "auth.docker.io": "container registry authentication",
    "cloudfront-index.crates.io": "crates.io sparse index, reached by cargo-binstall",
    "d3ipk8a4rcghwr.cloudfront.net": "Docker Hub image layer CDN",
    "glb-db52c2cf8be544.github.com": "GitHub Actions service, reached by the runner's node process",
    "blob.bl5prdstrz24a.store.core.windows.net": "Actions cache/artifact blob storage, reached by the runner's node process",
    "blob.blz25prdstrz09a.store.core.windows": "Actions cache/artifact blob storage, reached by the runner's node process (the name is truncated in the recorded flow)",
}

FALLBACK_REASON = "no reason recorded for this destination beyond the observation below"


def print_group(grouped, classification, destinations=None):
    destinations = destinations or grouped[classification]
    for destination in sorted(destinations):
        print(f"  - destination: {destination}")
        print(f"    reason: {REASONS.get(destination, FALLBACK_REASON)}")
        print("    observed:")
        for job, step, process in sorted(
            grouped[classification][destination],
            key=lambda k: (k[0], k[1] or "", k[2] or ""),
        ):
            print(f"      - job: {job}")
            print(f"        process: {process}")
            print(f"        step: {step if step is not None else 'outside any workflow step'}")


def load():
    with open(query.DEFAULT_EVIDENCE) as handle:
        records = [json.loads(line) for line in handle if line.strip()]
    for record in records:
        record["classification"] = query.classify(record)
    return records


def render():
    records = load()
    jobs = sorted({f"{r['workflow']} / {r['job']}" for r in records})
    profiles = len({r["profile_id"] for r in records})
    runs = len({r["run_id"] for r in records})
    commits = len({r["commit"] for r in records})

    print("# Proposed CI egress allowlist for garnet-labs/codex.")
    print("#")
    print("# Generated by .garnet/tools/build_allowlist.py from")
    print("# .garnet/evidence/actions.ndjson. Every rule is a destination a recorded CI")
    print("# job actually reached, with the process and workflow step that reached it.")
    print("# Nothing here is inferred from reading the workflow files.")
    print("#")
    print(f"# Scope: {profiles} job profiles across {runs} runs and {commits} commits.")
    for job in jobs:
        print(f"#   {job}")
    print("# Jobs that were never recorded are absent, not permitted. See")
    print("# .garnet/coverage.md for what is and is not recorded.")
    print("#")
    print("# Proposal. Not applied to any enforcement point.")
    print()
    print("version: 1")
    print("repository: garnet-labs/codex")
    print()
    print("# Egress this repository's own CI work performed, under a named workflow step.")
    print("allow:")

    grouped = collections.defaultdict(lambda: collections.defaultdict(set))
    for record in records:
        grouped[record["classification"]][record["destination"]].add(
            (record["job"], query.step_name(record), record["process"])
        )

    print_group(grouped, "workload")

    print()
    print("# Traffic the runner's own action machinery performed, not repository workload.")
    print("actions_service:")
    print_group(grouped, "actions-service")

    print()
    print("# Pulled by the docker daemon, not by a workflow step.")
    print("container_registry:")
    named = [d for d in grouped["container-runtime"] if not d[0].isdigit()]
    print_group(grouped, "container-runtime", named)
    unnamed = [d for d in grouped["container-runtime"] if d[0].isdigit()]
    print(f"  # {query.bare_address_note(len(unnamed))}")

    print()
    print("# Reached by the hosted runner, the platform, or the DNS resolver, outside any")
    print("# workflow step. Listed for whoever owns the runner network, not for this")
    print("# repository: the addresses rotate between runs, so pinning them produces")
    print("# allowlist churn rather than control.")
    print("runner_infrastructure:")
    for classification in ("runner-substrate", "dns-resolver", "azure-imds", "azure-wireserver"):
        destinations = sorted(grouped[classification])
        if not destinations:
            continue
        print(f"  - class: {classification}")
        print(f"    count: {len(destinations)}")
        print("    destinations:")
        for destination in destinations:
            processes = sorted(
                {p for _, _, p in grouped[classification][destination] if p}
            )
            print(f"      - {destination}  # via {', '.join(processes) or 'no named process'}")


def main():
    output = io.StringIO()
    with contextlib.redirect_stdout(output):
        render()
    rendered = output.getvalue()
    try:
        import yaml
    except ImportError:
        pass
    else:
        try:
            yaml.safe_load(rendered)
        except Exception as exc:
            print(f"generated allowlist is invalid YAML: {exc}", file=sys.stderr)
            return 1
    sys.stdout.write(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
